# Generated by Django 3.1.7 on 2021-03-11 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='Enter your first name', max_length=25)),
                ('lastName', models.CharField(default='Enter your last name', max_length=25)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('email', models.EmailField(default='', max_length=254)),
                ('first', models.BooleanField(default=True)),
                ('Department', models.CharField(choices=[('Behavioral Sciences and Leadership', 'Behavioral Sciences and Leadership'), ('Chemistry and Life Science', 'Chemistry and Life Science'), ('Civil and Mechanical Engineering', 'Civil and Mechanical Engineering'), ('Electrical Engineering and Comptuer Science', 'Electrical Engineering and Comptuer Science'), ('English and Philosophy', 'English and Philosophy'), ('Foreign Languages', 'Foreign Languages'), ('Geography and Environmental Engineering', 'Geography and Environmental Engineering'), ('History', 'History'), ('Law', 'Law'), ('Mathematical Sciences', 'Mathematical Sciences'), ('Physics and Nuclear Engineering', 'Physics and Nuclear Engineering'), ('Social Sciences', 'Social Sciences'), ('Systems Engineering', 'Systems Engineering'), ('Independent', 'Independent')], default='Independent', max_length=50)),
                ('Major', models.CharField(default='Undeclared', max_length=50)),
                ('Minor', models.CharField(blank=True, max_length=50, null=True)),
                ('interest', models.TextField(default='What academic or commercial areas are you interested in?')),
                ('expertise', models.TextField(default='Do you have any niche skills? For example: I can design and 3D print on SolidWorks.')),
                ('research_goals', models.TextField(default='What do you want to get out of reserach? For example, you may be interested in research purely to pursue passion, or you may want to work towards a graduate school scholarship')),
                ('lookingFor', models.CharField(choices=[('a research team to join.', 'Established Research Team'), ('a project to work on.', 'A fun project'), ('faculty to work under.', 'A faculty mentor'), ('nothing at the moment.', 'Nothing'), ('motivated cadets.', 'Recruiting Cadets'), ('anyone who needs help.', 'I want to help other people'), ('cadets looking to do research for three or four years.', 'Cadets interested in research that works towards a scholarship')], default='nothing at the moment.', max_length=75)),
                ('title', models.CharField(choices=[('Faculty', 'Faculty'), ('Cadet', 'Cadet')], default='Cadet', max_length=50)),
                ('twitter', models.CharField(default='@', max_length=30)),
                ('gradYear', models.IntegerField(blank=True, default=2023)),
                ('company', models.CharField(blank=True, default='', max_length=2)),
                ('phone', models.IntegerField(default=11111111111)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
