# Generated by Django 3.1.7 on 2021-03-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210307_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gradYear',
            field=models.IntegerField(blank=True, default=2023),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=11111111111),
        ),
    ]
