# Generated by Django 3.1.7 on 2021-03-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Major',
            field=models.CharField(default='Undeclared', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='Minor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
