# Generated by Django 3.1.7 on 2021-03-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210307_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Major',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Minor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gradYear',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lookingFor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='research_goals',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
    ]
