# Generated by Django 3.1.7 on 2021-03-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210307_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expertise',
            field=models.TextField(default='Do you have any niche skills? For example: I can design and 3D print on SolidWorks.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.TextField(default='What academic or commercial areas are you interested in?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='research_goals',
            field=models.TextField(default='What do you want to get out of reserach? For example, you may be interested in research purely to pursue passion, or you may want to work towards a graduate school scholarship'),
        ),
    ]
