# Generated by Django 3.1.7 on 2021-03-25 22:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210325_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expertise',
            field=models.TextField(default='You have expertise in...', verbose_name='Please list Your Areas of Expertise (separate by commas)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.CharField(default='', max_length=25, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gradYear',
            field=models.IntegerField(blank=True, default=2023, null=True, verbose_name='Graduation Year'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.TextField(default='Your academic or commmercial interests are...', verbose_name='What Are Your Interests?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastName',
            field=models.CharField(default='', max_length=25, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lookingFor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a research team to join.', 'an established Research Team'), ('a project to work on.', 'a fun project to work on'), ('faculty to work under.', 'a faculty mentor'), ('nothing at the moment.', 'nothing at the moment'), ('start project', 'to start a research project'), ('anyone who needs help.', 'the opportunity to help other people however I can'), ('cadets looking to do research for three or four years.', 'cadets interested in research that works towards a scholarship')], max_length=184),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default='', verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='research_goals',
            field=models.TextField(default='Your research goals are...', verbose_name='What Do You Want To Get Out Of Research?'),
        ),
    ]
