# Generated by Django 3.1.7 on 2021-03-27 17:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210325_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Major',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='expertise',
            field=models.TextField(null=True, verbose_name='Please list Your Areas of Expertise (separate by commas)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=models.TextField(null=True, verbose_name='What Are Your Interests?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lookingFor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('a research team to join.', 'an established Research Team'), ('a project to work on.', 'a fun project to work on'), ('faculty to work under.', 'a faculty mentor'), ('nothing at the moment.', 'nothing at the moment'), ('start project', 'to start a research project'), ('anyone who needs help.', 'the opportunity to help other people however I can'), ('cadets looking to do research for three or four years.', 'cadets interested in research that works towards a scholarship'), ('cadets who want to join a project.', 'cadets who want to join a project'), ('AIADs.', 'AIADs')], max_length=226, verbose_name='What Are You Currently Looking For?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='research_goals',
            field=models.TextField(null=True, verbose_name='What Do You Want To Get Out Of Research?'),
        ),
    ]
