# Generated by Django 3.1.7 on 2021-03-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210307_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(default='Enter your first name', max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(default='Enter your last name', max_length=25),
        ),
    ]
