# Generated by Django 3.1.7 on 2021-03-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ifCadet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='ifFaculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(default='@', max_length=30),
        ),
    ]
