# Generated by Django 3.1.7 on 2021-03-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210307_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ifCadet',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ifFaculty',
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Cadet', 'Faculty')], default='Cadet', max_length=50),
        ),
    ]
