# Generated by Django 3.1.7 on 2021-03-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210307_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lookingFor',
            field=models.CharField(choices=[('a research team to join.', 'Established Research Team'), ('a project to work on.', 'A fun project'), ('faculty to work under.', 'A faculty mentor'), ('nothing at the moment.', 'Nothing'), ('motivated cadets.', 'Recruiting Cadets'), ('anyone who needs help.', 'I want to help other people'), ('cadets looking to do research for three or four years.', 'Cadets interested in research that works towards a scholarship')], default='nothing at the moment.', max_length=75),
        ),
    ]
