# Generated by Django 3.1.7 on 2021-03-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectTag',
            field=models.CharField(choices=[('d', 'Data Analysis'), ('p', '3D Printing'), ('r', 'Robotics'), ('c', 'Coding'), ('f', 'Frauds, AKA Law majors')], default='f', max_length=32),
        ),
    ]
