# Generated by Django 3.1.7 on 2021-03-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bPic',
            field=models.ImageField(default=True, upload_to='uploads'),
        ),
    ]
