# Generated by Django 3.1.7 on 2021-03-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_projecttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='CIC_OIC',
            field=models.CharField(default='Nobody', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='Purpose',
            field=models.TextField(default='nobody'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='currentlyWorkingOn',
            field=models.TextField(default='nobody'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='ifRecruting',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='numUsers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
