# Generated by Django 3.1.7 on 2021-03-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210306_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectTag',
            field=models.CharField(choices=[('Data Analysis', 'Data Analysis'), ('3D Printing', '3D Printing'), ('Robotics', 'Robotics'), ('Coding', 'Coding'), ('Frauds', 'Frauds, AKA Law majors')], default='Frauds', max_length=32),
        ),
    ]
