# Generated by Django 3.1.7 on 2021-03-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_recruiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_admin',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='recruiting',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50),
        ),
    ]
