# Generated by Django 3.1.7 on 2021-03-27 17:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_uprojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bPic',
            field=models.ImageField(default='defaultproban.jpg', upload_to='project_banner', verbose_name='Choose Your Project Banner Picture'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', verbose_name='Please give a brief description of your project, progress, team, and goals.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(default='defaultlogo.jpg', upload_to='project_logo', verbose_name='Choose Your Project Logo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lookingFor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Expert Cadets.', 'motivated cadets with niche expertise.'), ('Any cadet who wants to help.', 'cadets who want to learn and help.'), ('an engineering cadet.', 'an engineering Cadet'), ('a cadet with a scientific background.', 'a cadet with a scientific background'), ('cadets with programming experience.', 'cadets with programming experience'), ('Stem interests.', 'cadets with an interest in STEM.'), ('scholarship', 'cadets seeking scholarships from research'), ('a lot of work.', 'cadets who can work 10-20 hours a week'), ('anyone', 'anyone!'), ('Nothing', 'nothing at the moment')], max_length=197, verbose_name='What Does This Project Need'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectTag',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Data Analysis', 'Data Analysis'), ('3D Printing', '3D Printing'), ('Robotics', 'Robotics'), ('Coding', 'Coding'), ('Science', 'Science'), ('Drones', 'Drones'), ('Math', 'Math'), ('Chemistry', 'Chemistry'), ('Nuclear Engineering', 'Nuclear Engineering'), ('Physics', 'Physics'), ('Photonics', 'Photonics'), ('MATLAB', 'MATLAB'), ('SolidWorks', 'SolidWorks'), ('Writing', 'Writing'), ('Graphic Design', 'Graphic Design'), ('Design', 'Design'), ('Robotics', 'Robotics'), ('Business', 'Business'), ('Stocks', 'Stocks'), ('Hacking', 'Hacking'), ('Law', 'Law Studies'), ('Coding', 'Coding'), ('Environmental', 'Environment'), ('Lifestyle', 'Lifestyle'), ('Kinesiology', 'Kinesiology'), ('Health', 'Health'), ('Sleep', 'Sleep'), ('Psychology', 'Psychology'), ('Material Science', 'Material Science'), ('Batteries', 'Batteries'), ('Energy', 'Energy'), ('Fiber Optics', 'Fiber Optics'), ('Space', 'Space'), ('Autonomous Vehicles', 'Autonomous Vehicles'), ('Biology', 'Biology')], max_length=342, verbose_name='Choose Up To 5 Tags'),
        ),
        migrations.AlterField(
            model_name='project',
            name='purpose',
            field=models.CharField(default='', max_length=50, verbose_name="Enter your project's purpose"),
        ),
        migrations.AlterField(
            model_name='project',
            name='recruiting',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50, verbose_name='Is This Project Currently Recruiting?'),
        ),
        migrations.AlterField(
            model_name='uprojects',
            name='ifAdmin',
            field=models.BooleanField(default=False, null=True, verbose_name='Do you want this user to be a project Admin?'),
        ),
    ]
