# Generated by Django 3.1.7 on 2021-03-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20210327_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True, verbose_name='Please give a brief description of your project, progress, team, and goals.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='purpose',
            field=models.CharField(max_length=50, null=True, verbose_name="Enter your project's purpose"),
        ),
    ]
