# Generated by Django 3.1.7 on 2021-03-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_auto_20210313_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ifViewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.URLField(blank='', default='', null=''),
        ),
    ]
