# Generated by Django 3.1.7 on 2021-03-25 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0012_project_status'),
        ('comments', '0001_initial'),
        ('departments', '0001_initial'),
        ('teams', '0001_initial'),
        ('AIAD', '0002_auto_20210325_1020'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcomment',
            name='teamComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='projectComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='departmentcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
        migrations.AddField(
            model_name='departmentcomment',
            name='departmentComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AddField(
            model_name='commentaiad',
            name='aiadComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIAD.aiad'),
        ),
        migrations.AddField(
            model_name='commentaiad',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
