# Generated by Django 3.1.7 on 2021-03-06 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210306_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userid',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userid',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userid',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userid',
            name='gradYear',
        ),
        migrations.RemoveField(
            model_name='userid',
            name='lastName',
        ),
        migrations.AddField(
            model_name='userid',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ubio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
