# Generated by Django 3.1.7 on 2021-03-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210315_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprojects',
            name='ifAccepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='uprojects',
            name='ifAdmin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
