# Generated by Django 3.1.7 on 2021-03-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210315_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projdepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='projdepartment',
            name='project',
        ),
        migrations.RemoveField(
            model_name='udeparment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='udeparment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='projDepartment',
        ),
        migrations.DeleteModel(
            name='uDeparment',
        ),
    ]
