# Generated by Django 3.1.7 on 2021-03-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210325_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uProjects',
        ),
    ]
