# Generated by Django 3.1.7 on 2021-03-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projdepartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubio',
            name='bPic',
        ),
        migrations.RemoveField(
            model_name='ubio',
            name='uPic',
        ),
        migrations.AddField(
            model_name='uprojects',
            name='ifAccepted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
