# Generated by Django 3.1.7 on 2021-03-25 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('AIAD', '0001_initial'),
        ('departments', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamaiad',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='postsaiad',
            name='AIAD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIAD.aiad'),
        ),
        migrations.AddField(
            model_name='postsaiad',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='depaiad',
            name='AIAD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIAD.aiad'),
        ),
        migrations.AddField(
            model_name='depaiad',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
