# Generated by Django 3.1.7 on 2021-03-25 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mission', models.CharField(max_length=100)),
                ('depBanner', models.ImageField(blank=True, default='', upload_to='department_banner')),
                ('depLogo', models.ImageField(blank=True, default='', upload_to='department_logo')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived'), ('Deleted', 'Deleted')], default='Active', max_length=50)),
                ('dac', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='DAC', to=settings.AUTH_USER_MODEL)),
                ('departmentHead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='departmentHead', to=settings.AUTH_USER_MODEL)),
                ('deputyHead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deputyHead', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='uDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='projDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
