# Generated by Django 3.1.7 on 2021-03-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('numUser', models.IntegerField()),
                ('bPic', models.ImageField(upload_to='uploads')),
                ('purpose', models.TextField()),
                ('projectTag', models.CharField(choices=[('Data Analysis', 'Data Analysis'), ('3D Printing', '3D Printing'), ('Robotics', 'Robotics'), ('Coding', 'Coding'), ('Frauds', 'Frauds, AKA Law majors')], default='Frauds', max_length=32)),
            ],
            options={
                'verbose_name_plural': 'projects',
            },
        ),
    ]
