# Generated by Django 3.1.7 on 2021-03-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Leader',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(default='defaultlogo.jpg', upload_to='project_logo'),
        ),
        migrations.AddField(
            model_name='project',
            name='lookingFor',
            field=models.CharField(choices=[('motivated cadets with niche expertise.', 'Expert Cadets'), ('cadets who want to learn and help.', 'Any cadet who wants to help'), ('an engineering cadet.', 'Engineering Cadet'), ('a cadet with a scientific background.', 'Scientific background'), ('cadets with programming experience.', 'Coding Background')], default='an engineering cadet,', max_length=75),
        ),
        migrations.AddField(
            model_name='project',
            name='projectDepartment',
            field=models.CharField(choices=[('Behavioral Sciences and Leadership', 'Behavioral Sciences and Leadership'), ('Chemistry and Life Science', 'Chemistry and Life Science'), ('Civil and Mechanical Engineering', 'Civil and Mechanical Engineering'), ('Electrical Engineering and Comptuer Science', 'Electrical Engineering and Comptuer Science'), ('English and Philosophy', 'English and Philosophy'), ('Foreign Languages', 'Foreign Languages'), ('Geography and Environmental Engineering', 'Geography and Environmental Engineering'), ('History', 'History'), ('Law', 'Law'), ('Mathematical Sciences', 'Mathematical Sciences'), ('Physics and Nuclear Engineering', 'Physics and Nuclear Engineering'), ('Social Sciences', 'Social Sciences'), ('Systems Engineering', 'Systems Engineering'), ('Independent', 'Independent')], default='Independent', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='bPic',
            field=models.ImageField(default='defaultproban.jpg', upload_to='project_banner'),
        ),
    ]
