# Generated by Django 3.1.7 on 2021-03-14 03:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_auto_20210313_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='admins',
        ),
        migrations.AddField(
            model_name='member',
            name='admins',
            field=models.ManyToManyField(limit_choices_to={'is_admin': True}, to=settings.AUTH_USER_MODEL),
        ),
    ]
