# Generated by Django 3.1.7 on 2021-03-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_notification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank='', default='', max_length=500),
        ),
    ]
